### ISSUE TITLE
will the older version 6,7 be supported 

### ISSUE THREAD

**Issue by youdmeng** [openjdk/aarch64-port#7]
will the older version 6,7 be supported. it's very important for me

**Comment by gnu-andrew** [comment]
For OpenJDK 7, AArch64 support is maintained in IcedTea 2: https://icedtea.classpath.org/hg/release/icedtea7-forest-2.6/hotspot/
For OpenJDK 6, there hasn't been an update since the end of 2018 and there is no intention to backport AArch64 support there.
