### ISSUE TITLE
On MacOS DetachCurrentThread kills non-Java code in MAP_JIT areas.

### ISSUE THREAD

**Issue by Yehouda** [openjdk/aarch64-port#9]
The call to enable_wx_from_exec inside jni_DetachCurrentThread https://github.com/openjdk/aarch64-port/blob/47396be77b0d567fd3fc99736454da834bca4c1f/src/hotspot/share/prims/jni.cpp#L4095  means that any other code in MAP_JIT areas on the same thread doesn't work anymore.

We have code running in areas mapped with MAP_JIT, and sometimes use Java, and when trying to use Zulu, once iit cals DetachCurrentThread it dies.

Why does it has to doit?

**Comment by AntonKozlov** [comment]
The rationale behind the switch is follows. At the beginning, native thread has undefined pthread_jit_write_protect_np state. Once the thread attached, the W^X state is managed by VM. After detach no java code can be executed on the thread, so it's initialized to Write mode, roughly approximating uninitialized state. If the thread is going to execute a JIT code not managed by the VM, the thread should also manage W^X mode as needed.

But I suspect there may be a problem in this code. Do you see a crash in the DetachCurrentThread itself? Any issue with missing W^X mode management should occur later, on execution attempt of another JIT code.

**Comment by Yehouda** [comment]
I don't think the initial state is undefined. It should be protected, so the code can be executed. It should be unprotected only in the scope of code that modify code (and the modifying code cannot be itself in MAP_JIT). 

I see the crash after returning from DetachCurrentThread, because the caller code itself is n MAP_JIT area.

**Comment by Yehouda** [comment]
The Apple document below clearly assumes that the default state is protected, and you need to call pthread_jit_write_protect_np with 0  before writing code and then restore it. 

 call https://developer.apple.com/documentation/apple_silicon/porting_just-in-time_compilers_to_apple_silicon?language=objc

**Comment by AntonKozlov** [comment]
I see, the assumption looks especially reasonable in this use-case. To return to JITed code, another transition should be made to executable state before the exit from DetachCurrentThread. Now we tie JIT protection mode to java thread state, it leads to rather simple model which pays (e.g. `thread->exit()` may call to java code, so we need more protection mode changes). Thanks for reporting, I'll implement the fix shortly.

**Comment by AntonKozlov** [comment]
Hi @Yehouda, please look at the test in #10. Does it describe the problematic behavior correctly?

**Comment by Yehouda** [comment]
>  
>  Hi @Yehouda, please look at the test in #10. Does it describe the problematic behavior correctly?
>  

It looks ok, but it wil end up with an exception. Maybe should add
code to catch the exception and give a clear message indicating that
it got the expected error. 

I also tend to use longer variable names....

**Comment by AntonKozlov** [comment]
Oh, I mean, the fix fixes the test. But does it fix your application? Or, taking it another way, does the test capture important aspects of the application, which lead to the issue. I hope so.

> it will end up with an exception.

What exception do you refer to? Let's move the code discussion to the PR. 

Thanks.

**Comment by Yehouda** [comment]
You asked to look at the test, it looks ok. without the fix it will crash like our code used to crash. 
By now we call DeatchCurrentThread from a code in a text segment (not JIT), and then immediately protect the code, so it works around the problem anyway, and it is not going to crash for us. 

Without the fix the test will get exception when trying to executed the trampoline in the JIT area. 

Send the next message to the PR, I will answer it there.

**Comment by AntonKozlov** [comment]
> Without the fix the test will get exception when trying to executed the trampoline in the JIT area.

Got it. So it should be resolved.
